### PR TITLE
More efficient EXP sum

### PR DESCRIPTION
**Pull request by calebj**
You shouldn't use a for loop to sum things when you can avoid it. This is one such case.

### CODE REVIEW

**Comment by calebj** [comment]
I'm not sure why, but my local git shows only a few changed lines. It looks like the line endings got changed somewhere between me and git.

**Comment by AznStevy** [comment]
I'm too lazy to search for what you changed. How is using sum more efficient? Both are O(N).

**Comment by AznStevy** [comment]
I assume that's what your did, but again, I can't see it at the moment.

**Comment by calebj** [comment]
I replaced occurrences of

```
exp = 0
for i in range(level):
    exp += self._required_exp(i)
```

with

```
exp = self._level_exp(level)
```

where _level_exp uses the formula for the sum of an arithmetic sequence:

```
def _level_exp(self, level: int):
    return level*LEVEL_CONSTANT + LEVEL_COEFFICIENT*level*(level-1)//2
```

**Pull request closed without merging**
